chores(claim): remove x/claim module
EscanBE/evermint pull request #73
Opened 2024-01-10 10:34 UTC by ronal999999

2024-01-11 07:52 UTC, VictorEscan requested changes

2024-01-11 07:52 UTC, VictorEscan commented on CHANGELOG.md
> +- (claim) [#71](https://github.com/EscanBE/evermint/pull/73) Remove `x/claim` module
```suggestion
- (claims) [#73](https://github.com/EscanBE/evermint/pull/73) Remove `x/claims` module
```

2024-01-11 07:52 UTC, VictorEscan commented on app/app.go
> +		chainApp.IBCKeeper.ChannelKeeper, // ICS4 Wrapper: claims IBC middleware
```suggestion
		chainApp.IBCKeeper.ChannelKeeper, // No ICS4 wrapper
```

2024-01-11 07:52 UTC, VictorEscan commented on ibc/utils_test.go
> +		//},
Why delete test?

2024-01-11 07:52 UTC, VictorEscan commented on x/erc20/keeper/ibc_callbacks_integration_test.go
> +	//})
```suggestion
```
Delete this test

2024-01-11 07:52 UTC, VictorEscan commented on app/app.go
>  		// NOTE: staking requires the claiming hook
```suggestion
```
Delete this comment

2024-01-11 07:52 UTC, VictorEscan commented on x/erc20/keeper/ibc_callbacks_test.go
> +				moduleAcc := suite.app.AccountKeeper.GetModuleAccount(suite.ctx, types.ModuleName)
TODO check logic

2024-01-11 07:52 UTC, VictorEscan commented on x/erc20/keeper/ibc_callbacks_test.go
> +			name: "ibc conversion - sender == receiver",
TODO check logic

2024-01-11 07:52 UTC, VictorEscan commented on x/erc20/keeper/ibc_callbacks.go
> -	claimsParams := k.claimsKeeper.GetParams(ctx)
TODO: check logic & behavior

2024-01-11 07:52 UTC, VictorEscan commented on x/erc20/keeper/utils_test.go
>  	suite.Require().NoError(err)
Delete this line

2024-01-11 08:10 UTC, VictorEscan requested changes

2024-01-11 08:10 UTC, VictorEscan commented on ibc/utils_test.go
> +		//},
```suggestion
		{
			"valid - any amount",
			channeltypes.Packet{
				Data: transfertypes.ModuleCdc.MustMarshalJSON(
					&transfertypes.FungibleTokenPacketData{
						Sender:   "cosmos1qql8ag4cluz6r4dz28p3w00dnc9w8ueulg2gmc",
						Receiver: marker.ReplaceAbleAddress("evm1x2w87cvt5mqjncav4lxy8yfreynn273xe08fl7"),
						Amount:   "1",
					},
				),
			},
			"1",
			false,
		},
```

2024-01-12 09:06 UTC, VictorTrustyDev commented on x/erc20/keeper/ibc_callbacks_test.go
> +			name: "ibc conversion - sender == receiver",
Ref #79

2024-01-12 09:07 UTC, VictorTrustyDev commented on x/erc20/keeper/ibc_callbacks.go
> -	claimsParams := k.claimsKeeper.GetParams(ctx)
Ref #79

2024-01-16 14:53 UTC, VictorEscan approved these changes

2024-01-16 14:53 UTC, merged